Web/Controllers/LinhVucController.cs
using Infrastructure.Data;
using Infrastructure.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Web.Controllers
{
    public class LinhVucController:Controller
    {
        private readonly DataConText _context;
        public LinhVucController(DataConText context)
        {
            _context = context;
        }
         public async Task<IActionResult> Index(string searching)
        {
           
            return View(await _context.tbLinhVuc.Where(x => x.MaLinhVuc.Contains(searching) || searching == null).ToListAsync()); 
        }
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();
			var linhVuc = await _context.tbLinhVuc
				.FirstOrDefaultAsync(m => m.Id == id);
			if (linhVuc==null) return NotFound();
            return View(linhVuc);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,MaLinhVuc,TenLinhVuc,MoTa")] LinhVuc linhVuc)
        {
            if(ModelState.IsValid)
            {
                _context.Add(linhVuc);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));

            }return View(linhVuc);
        }
        public async Task<IActionResult> Edit(int? id) {
            if(id==null) return NotFound();
            var linhVuc =await _context.tbLinhVuc.FindAsync(id);
            if(linhVuc==null) return NotFound();
            return View(linhVuc);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,MaLinhVuc,TenLinhVuc,MoTa")] LinhVuc linhVuc)
        {
            if (id !=linhVuc.Id) return NotFound();
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(linhVuc);
                    await _context.SaveChangesAsync();
                }
                catch(DbUpdateConcurrencyException)
                {
                    if (!LinhVucExists(linhVuc.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }

                }
                return RedirectToAction(nameof(Index));
            }
            return View(linhVuc);

        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id==null) return NotFound();
            var linhVuc = await _context.tbLinhVuc.FirstOrDefaultAsync(m=>m.Id==id);
            if (linhVuc == null) return NotFound();
            return View(linhVuc);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            var linhVuc= await _context.tbLinhVuc.FindAsync(id);
            if(linhVuc!=null) _context.tbLinhVuc.Remove(linhVuc);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }



        private bool LinhVucExists(int id)
        {
            return _context.tbLinhVuc.Any(x => x.Id == id);
        }
    }
}

Web/Views/LinhVuc/Create.cshtml
@model Infrastructure.Models.LinhVuc
@{
	ViewData["Title"] = "Create";
}
<h1> Create</h1>
<h4>Linh Vuc</h4>
<br />
<div class="row"> 
	<div class="col-4">
		<form asp-action="Create">
			<div asp-validation-summary="ModelOnly" class=" text-danger"></div>
		
			<div class="form-group">
				<label asp-for="MaLinhVuc" class="control-label"></label>
				<input asp-for="MaLinhVuc" class="form-control" />
				<span asp-validation-for="MaLinhVuc" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="TenLinhVuc" class="control-label"></label>
				<input asp-for="TenLinhVuc" class="form-control" />
				<span asp-validation-for="TenLinhVuc" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="MoTa" class="control-label"></label>
				<input asp-for="MoTa" class="form-control" />
				<span asp-validation-for="MoTa" class="text-danger"></span>
			</div>
			<input type="submit" class="btn btn-primary" />

		</form>
	</div>
	
</div>
<div>
	<a asp-action="Index">Back to list</a>
</div>
@section Scripts{
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web/Views/LinhVuc/Delete.cshtml
@model Infrastructure.Models.LinhVuc
@{
	ViewData["Title"] = "Delete";
}
<h1>Delete</h1>
<h4> LinhVuc</h4>
<br />
<
<dl class="row">
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.MaLinhVuc)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.MaLinhVuc)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.TenLinhVuc)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.TenLinhVuc)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.MoTa)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.MoTa)
    </dd>
</dl>
<div>
	<form asp-action="Delete">
		<input type="hidden" asp-for="Id" />
		<input type="submit" value="Delete" class="btn btn-danger" />
		<a asp-action="Index">Back to list</a>
	</form>
</div>

Web/Views/LinhVuc/Details.cshtml
@model Infrastructure.Models.LinhVuc
@{
	ViewData["Title"] = "Details";
}
<h1>
	Details
</h1>
<h4>LinhVuc</h4>
<br />
<<dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaLinhVuc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaLinhVuc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TenLinhVuc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TenLinhVuc)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MoTa)
        </dd>
    </dl>
<div>
	<a asp-action="Edit">Edit</a>
	<a asp-action="Index"> Back to list</a>
</div>

Web/Views/LinhVuc/Edit.cshtml
@model Infrastructure.Models.LinhVuc
@{
	ViewData["Title"] = "Edit";
}
<h1>Edit</h1>
<h4>LinhVuc</h4>
<br />
<div class="row">
	<div class="col-4">
		<form asp-action="Edit">
			<div asp-validation-summary="ModelOnly"></div>
			
			<div class=" form-group">
				<label asp-for="MaLinhVuc" class="control-label"></label>
				<input asp-for="MaLinhVuc" class="form-control" />
				<<span asp-validation-for="MaLinhVuc"></span>
			</div>
			<div class=" form-group">
				<label asp-for="TenLinhVuc" class="control-label"></label>
				<input asp-for="TenLinhVuc" class="form-control" />
				<<span asp-validation-for="TenLinhVuc"></span>
			</div>
			<div class=" form-group">
				<label asp-for="MoTa" class="control-label"></label>
				<input asp-for="MoTa" class="form-control" />
				<<span asp-validation-for="MoTa"></span>
			</div>
			<input type="submit" class="btn btn-primary" />

		</form>
	</div>
</div>
<div>
	<a asp-action="Index">Back to list</a>
</div>

Web/Views/LinhVuc/Index.cshtml
@model IEnumerable<Infrastructure.Models.LinhVuc>
@{
	ViewData["Title"] = "Index";
}
<h1>
	Index
</h1>
<p>
	<a asp-action="Create" >Create New</a>
</p>
@using (Html.BeginForm("Index","LinhVuc",FormMethod.Get))
{
	<div class="form-group">
		<b >Search</b>
		@Html.TextBox("searching")<input class="form-control btn btn-success w-20" type="submit" value="Search" />
	</div>

}
<table class="table  table-bordered table-striped" >
	<thead>
		<tr>
			
			<th>
				@Html.DisplayNameFor(model => model.MaLinhVuc)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.TenLinhVuc)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.MoTa)
			</th>
			
		</tr>
	</thead>
	<tbody>
		@if (Model.Count() == 0)
		{
			<tr>
				<td>NOT FOUND</td>
			</tr>
		}
		else
		{
			
		
			foreach(var item in Model)
			{
			<tr>
				
				<td>
					@Html.DisplayFor(modelItem => item.MaLinhVuc)
				</td>

				<td>
					@Html.DisplayFor(modelItem => item.TenLinhVuc)
				</td>

				<td>
					@Html.DisplayFor(modelItem => item.MoTa)
				</td>
				<td class="btn btn-group">
					<a asp-action="Edit" asp-route-id="@item.Id">Edit</a>|
					<a asp-action="Details" asp-route-id="@item.Id">Details</a>|
					<a asp-action="Delete" asp-route-id="@item.Id">Delete</a>

				</td>
			</tr>
		}
		}
	</tbody>
</table>